if (typeof coreleo === 'undefined') var coreleo = {};
if (typeof coreleo.util === 'undefined') coreleo.util = {};
if (typeof coreleo.ui === 'undefined') coreleo.ui = {};
if (typeof coreleo.ui.menu === 'undefined') coreleo.ui.menu = {};
if (typeof coreleo.ui.dialog === 'undefined') coreleo.ui.dialog = {};
if (typeof coreleo.ui.tabs === 'undefined') coreleo.ui.tabs = {};
if (typeof coreleo.mobile === 'undefined') coreleo.mobile = {};
if (typeof coreleo.mobile.util === 'undefined') coreleo.mobile.util = {};
if (typeof coreleo.mobile.util.selectmenu === 'undefined') coreleo.mobile.util.selectmenu = {};
if (typeof coreleo.mobile.util.table === 'undefined') coreleo.mobile.util.table = {};
if (typeof coreleo.mobile.util.input === 'undefined') coreleo.mobile.util.input = {};
if (typeof coreleo.event === 'undefined') coreleo.event = {};
if (typeof coreleo.event.poller === 'undefined') coreleo.event.poller = {};
if (typeof coreleo.console === 'undefined') coreleo.console = {};
